---
# - hosts: all
#   roles:
#     - { role: kubernetes/preinstall, tags: preinstall }

- hosts: bird-rr[0]
  roles:
    - role: multirack/upload-config
      etcd_authority: "{%for a in groups.etcd%}https://{{a}}:2379/{%if not loop.last%},{%endif%}{%endfor%}"
      tags: network

- hosts: bird-rr
  roles:
    - role: multirack/bird-container
      bgpd_mode: rr
      bgpd_container_tag: stable
      etcd_authority: "{%for a in groups.etcd%}https://{{a}}:2379/{%if not loop.last%},{%endif%}{%endfor%}"
      tags: network

- hosts: bird-node
  roles:
    - role: multirack/bird-container
      bgpd_mode: node
      bgpd_container_tag: stable
      etcd_authority: "{%for a in groups.etcd%}https://{{a}}:2379/{%if not loop.last%},{%endif%}{%endfor%}"
      tags: network

