---
#- debug: var=multirack_topology
- name: Install addition packages
  apt: name={{item}} state=latest
  with_items:
    - python-docker
- name: Download Route Redistributer container
  docker_image: name=xenolog/k8s-rr-container:{{ bgpd_container_tag }}
- block:
  - name: Configure and run RR
    template:
      src: bird_env.j2
      dest: /etc/bird-{{ bgpd_mode }}.env
    notify: restart bird-{{ bgpd_mode }}
  - template:
      src: bird-container_unit.j2
      dest: /etc/systemd/system/bird-{{ bgpd_mode }}.service
    notify:
      - reload systemd
      - restart bird-{{ bgpd_mode }}
  - service:
      name: bird-{{ bgpd_mode }}
      enabled: yes
      state: started
